### ISSUE TITLE
Grab file and folder name variables from latest published version

### ISSUE THREAD

**Issue by arttus** [BeerK0in/generator-gunbot#22]
Rather than specifying the version of gunbot in the code, I'm just wondering if it wouldn't be better to just check if there is a new version, then fill in the file and folder name variables from the new versions file name dynamically. 

That way you wouldn't have to update the generator-gunbot code install.sh, install-loud.sh and update.sh files every time a new version came out.

Fantastic project by the way, HUGE time saver.

**Comment by BeerK0in** [comment]
This would work if a new version is 100% compatible with the old structure. But as you see in Gunbot v3.3.4 the executables have been renamed and there is also a new tulind folder needed to run gunbot. So dynamically pull the release names would not save from editing the install scripts.
