### ISSUE TITLE
Errors in log after installing

### ISSUE THREAD

**Issue by nlegall** [BeerK0in/generator-gunbot#25]
Getting these errors from glog
0|BTC_ETH_ | Unhandled rejection Error: statusCode 422
0|BTC_ETH_ |     at Object.console./snapshot/Users/Enrico/Desktop/xBot_v2.9.3/poloniex.js.module.exports.Market.getLastBuyRate.poloniex.returnTradeHistory [as callbac
k] (evalmachine.<anonymous>:0:0)
0|BTC_ETH_ |     at /snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/async/dist/async.js:2243:31
0|BTC_ETH_ |     at /snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/async/dist/async.js:906:16
0|BTC_ETH_ |     at Request._callback (/snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/plnx/lib/index.js:134:7)
0|BTC_ETH_ |     at Request.self.callback (/snapshot/Users/Enrico/Desktop/xBot_v2.9.3/node_modules/request/request.js:188:22)
0|BTC_ETH_ |     at emitTwo (events.js:106:13)
0|BTC_ETH_ |     at Request.emit (events.js:192:7)

**Comment by holodigm** [comment]
This is a Gunbot error and not related to anything in this repo. I'd suggest jumping into the forums to understand why this happens. https://gunthy.org/index.php?topic=65.0
